# Generated by Django 2.1.7 on 2019-02-14 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('text_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'essays',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('img_time', models.DateTimeField()),
                ('kind', models.CharField(choices=[('trace', '旅游'), ('movies', '电影'), ('books', '书籍'), ('anime', '动漫'), ('life', '生活')], max_length=50)),
                ('introduce', models.CharField(blank=True, max_length=255, null=True)),
                ('essay_rel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='its_images', to='blog.Essay')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('content', models.TextField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
