# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170808_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
