# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_message_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
    ]
