# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170809_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('text_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('img_time', models.DateTimeField()),
                ('kind', models.CharField(choices=[('trace', '旅游'), ('movies', '电影'), ('books', '书籍'), ('anime', '动漫'), ('life', '生活')], max_length=50)),
                ('introduce', models.CharField(blank=True, max_length=255, null=True)),
                ('essay_rel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay', to='blog.Essay')),
            ],
        ),
    ]
