# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_essay_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='essay_rel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='its_images', to='blog.Essay'),
        ),
    ]
